// facturar();
const catalogo = new Catalogo();
console.log(catalogo);
const papa = catalogo.adicionar("papa", 75);
const ajo = catalogo.adicionar("ajo", 35);
const zanahoria = catalogo.adicionar("zanahoria", 40);
const mandarina = catalogo.adicionar("mandarina", 50);
console.log(catalogo);
const carrito = new Carrito(catalogo);
console.log(carrito);
carrito.adicionarLinea(papa.id, 3);
carrito.adicionarLinea(ajo.id, 7);
carrito.adicionarLinea(zanahoria.id, 3);
carrito.adicionarLinea(mandarina.id, 3);
console.log(carrito);
carrito.adicionarLinea(papa.id, 7);
console.log(carrito);
